[package]
name = "spooky_bsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-init = "2.0.0"
byteorder = "1.4.3"
eyre = "0.6.7"
flate2 = "1.0.22"
num_enum = "0.5.7"