[package]
name = "spooky_bsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.22"
bytes = "1.1.0"
byteorder = "1.4.3"
num_enum = "0.5.4"